# Generated by Django 4.2.6 on 2023-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('website_link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('subtitle_for_company', models.TextField()),
                ('emp_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_required', models.TextField()),
                ('education', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('vacancy', models.PositiveIntegerField()),
                ('job_nature', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], max_length=50)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_date', models.DateField()),
            ],
        ),
    ]
